<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com._4point.utils</groupId>
	<artifactId>simple-excel</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Simple Excel Library</name>
	<description>Library that utilizes Apache POI to read Excel files simply.</description>
	<properties>
		<java.version>11</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<!-- Project Dependencies -->
		<apache-poi.version>5.5.1</apache-poi.version>
		<commons-collections4.version>4.5.0</commons-collections4.version>

		<!-- Testing Dependencies -->
		<junit.version>5.14.1</junit.version>
		<mockito.version>5.21.0</mockito.version>
		<hamcrest.version>3.0</hamcrest.version>
		<jimfs.version>1.3.0</jimfs.version>
	</properties>

	<distributionManagement>
		<repository>
			<id>github</id>
			<name>GitHub 4PointSolutions Apache Maven Packages</name>
			<url>https://maven.pkg.github.com/4PointSolutions/simple-excel</url>
		</repository>
	</distributionManagement>

	<dependencies>
		<!-- Project Dependencies -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>${apache-poi.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>${apache-poi.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
			<version>${commons-collections4.version}</version>
		</dependency>

		<!-- Testing Dependencies -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-library</artifactId>
			<version>${hamcrest.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.google.jimfs</groupId>
			<artifactId>jimfs</artifactId>
			<version>${jimfs.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>